CREATE TABLE ASSOCIADO
(
    ID   INT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100)    NOT NULL,
    CPF  VARCHAR(11)     NOT NULL
);

CREATE TABLE PAUTA
(
    ID          INT PRIMARY KEY NOT NULL,
    NOME        VARCHAR(100)    NOT NULL,
    DESCRICAO   VARCHAR(300)    NOT NULL,
    CADASTRO    TIMESTAMP       NOT NULL,
    ATUALIZACAO TIMESTAMP
);

CREATE TABLE SESSAO
(
    ID       INT PRIMARY KEY NOT NULL,
    ID_PAUTA INT             NOT NULL REFERENCES PAUTA (ID),
    FIM      TIMESTAMP       NOT NULL
);

CREATE TABLE VOTO
(
    ID           INT PRIMARY KEY NOT NULL,
    ID_SESSAO    INT             NOT NULL REFERENCES SESSAO (ID),
    ID_ASSOCIADO INT             NOT NULL REFERENCES ASSOCIADO (ID),
    VOTO         VARCHAR(3)      NOT NULL
);
